### ISSUE TITLE
Two TODOs

### ISSUE THREAD

**Issue by nubok** [mit-pdos/xv6-book#5]
In

> https://github.com/mit-pdos/xv6-book/blob/cfe48f65619c6bab0d8156bc37032455cd1901d1/trap.t#L339

`TODO: Replace SETGATE with real code.`

> https://github.com/mit-pdos/xv6-book/blob/cfe48f65619c6bab0d8156bc37032455cd1901d1/fs.t#L13

`	TODO: Explain the name sys_mknod.`

Perhaps someone wants "to really do the TODOs" so that they can be removed?

**Comment by kaashoek** [comment]
I think both are obsolete and i deleted them.
